#cloud-config
users:
  - name: debian
    groups: sudo, wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      # replace with your key
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH7TIhzQA3ijlmeBwP5CcriBP8M3CchPbC6DI301Nrc9
write_files:
  - path: /etc/ssh/sshd_config.d/port.conf
    content: |
      # SSHD configuration
      Port 1337
    permissions: '0600'
# mirror setup
apt:
  sources:
    kubernetes.list:
      source: "deb [signed-by=$KEY_FILE] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
      keyid: DE15B14486CD377B9E876E1A234654DA9A296436
      filename: kubernetes.list
    # we're using debian 11 packages because debian12 builds weren't available when making this guide
    crio.list:
     source: "deb [signed-by=$KEY_FILE] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.28/Debian_11/ /"
     keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
     filename: crio.list
    kubic.list:
     source: "deb [signed-by=$KEY_FILE] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/ /"
     keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
     filename: kubic.list
# install packages
package_update: true
packages:
    - [kubeadm, 1.28.2-1.1]
    - [kubelet, 1.28.2-1.1]
    - [kubectl, 1.28.2-1.1]
    - cri-o-runc
    - cri-o
runcmd:
    - |
      cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
      overlay
      br_netfilter
      EOF
    - |
      cat <<EOF | tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF
    - sudo modprobe overlay
    - sudo modprobe br_netfilter
    - sudo sysctl --system
    - sudo systemctl enable --now crio
    - sudo rm -rf "/etc/cni/net.d/*"